testing/task3/OnlineSofaProject/online_store_on_sofa_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store_app.urls')),
    path('accounts/', include('accounts_app.urls')),
    path('captcha/', include('captcha.urls')),
    path('management/', include('management_app.urls')),
]
handler403 = 'store_app.views.error_403'
handler404 = 'store_app.views.error_404'

testing/task3/OnlineSofaProject/store_app/urls.py
from django.conf import settings
from django.urls import path, re_path
from django.conf.urls.static import static
from .views import *
urlpatterns = [
    path('', HomepageView.as_view(), name='home'),

    path('product_details/<int:pk>/', ProductDetailsPageView.as_view(), name='product_details'),
    path('products_by_rubric/<int:pk>/', ProductsByRubricPageView.as_view(), name='products_by_rubric'),
    path('search_products', SearchProductsView.as_view(), name='search_products'),
    # product page
    path('add_new_comment', AddNewCommentView.as_view(), name='add_new_comment'),
    path('add_product_to_basket', AddProductToCartView.as_view(), name='add_product_to_basket'),
    # cart page
    path('user_cart_page', UserCartView.as_view(), name='user_cart_page'),
    path('delete_product_in_cart', DeleteProductInCartView.as_view(), name='delete_product_in_cart'),
    path('reduce_count_products', ReduceCountProductsView.as_view(), name='reduce_count_products'),
    path('increase_count_products', IncreaseCountProductsView.as_view(), name='increase_count_products'),
    # ordering
    path('ordering/payment_delivery', OrderingPaymentDeliveryView.as_view(), name='ordering_payment_delivery'),
    path('ordering/payment_online', OrderingPaymentOnlineView.as_view(), name='ordering_payment_online'),
    path('order_created/<int:encrypted_order_num>/<int:key>/', OrderCreatedView.as_view(), name='order_created'),
    path('history_orders', HistoryOrdersView.as_view(), name='history_orders'),
    path('pdf_details_order/<str:num_str>', GeneratePdfOrderDetailsView.as_view(), name='pdf_details_order'),
    # footer
    path('contacts/', ContactsPageView.as_view(), name='contacts'),
    path('feedback_form', FeedbackFormView.as_view(), name='feedback_form'),

    re_path(r'sorting_products/(?P<type_sorting>[a-z]+_[a-z]+)', ProductsBySortingView.as_view(),
            name='sorting_products'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

testing/task3/OnlineSofaProject/store_app/models/CartUser.py
from django.contrib.auth.models import User
from django.db import models

from .Product import Product


class CartUser(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, verbose_name='Никнейм покупателя')
    products = models.ManyToManyField(Product, verbose_name='Товары в корзине')

    class Meta:
        verbose_name_plural = 'Корзина пользователя с товарами'
        verbose_name = 'Товар в корзине'
        ordering = ['user']

    def __str__(self):
        return 'Корзина пользователя с товарами ' + self.user.username

testing/task3/OnlineSofaProject/store_app/models/Comment.py
from django.contrib.auth.models import User
from django.core import validators
from django.db import models

from .Product import Product


class Comment(models.Model):
    """Модель комментария к товару"""
    text_comment = models.TextField(blank=True, null=True, verbose_name='Комментарий')
    rating = models.PositiveSmallIntegerField(validators=[validators.MaxValueValidator(5)], verbose_name='Оценка')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар', related_name='comments')
    author_comment = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    date_comment = models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата комментирования')

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['product']

    def __str__(self):
        return self.product.title

testing/task3/OnlineSofaProject/store_app/models/FeedBackWithClient.py
from django.core import validators
from django.db import models


class FeedBackWithClient(models.Model):
    """Модель обращения клиентов с просьбой об обратной связи"""
    name_client = models.CharField(max_length=50, verbose_name='Имя клиента',
                                   validators=[validators.MinLengthValidator(5)])
    phone_client = models.CharField(max_length=15, verbose_name='Номер телефона для обратной связи')
    email_client = models.EmailField(verbose_name='Электронная почта для обратной связи',
                                     validators=[validators.MinLengthValidator(5)])

    question_client = models.TextField(verbose_name='Вопрос клиента', validators=[validators.MinLengthValidator(15)],
                                       null=True)
    given_feedback = models.BooleanField(verbose_name='Дана ли обратная связь?', default=False)

    def __str__(self):
        return f'Заявка на обратную связь №{str(self.pk).zfill(6)}'

    class Meta:
        verbose_name_plural = 'Заявки на обратную связь'
        verbose_name = 'Заявка на обратную связь'
        ordering = ['name_client', 'phone_client', 'email_client', 'given_feedback']

testing/task3/OnlineSofaProject/store_app/models/ImageProduct.py
from django.core import validators
from django.db import models

from .Product import Product


class ImageProduct(models.Model):
    """Модель изображения товара"""
    image = models.ImageField(null=True, blank=True, verbose_name='Изображения товара',
                              upload_to="images/store_app/products/",
                              validators=[validators.validate_image_file_extension])
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Товар')

    class Meta:
        verbose_name_plural = 'Изображения товаров'
        verbose_name = 'Изображение товара'
        ordering = ['product']

    def __str__(self):
        return self.product.title

testing/task3/OnlineSofaProject/store_app/models/ProductsInOrder.py
from django.db import models

from .Product import Product
from .Order import Order


class ProductsInOrder(models.Model):
    """Модель товаров в заказе"""
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name='Заказ', null=True, blank=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Название товара')
    count_product_in_order = models.PositiveIntegerField(verbose_name='Количество данного товара')

    def __str__(self):
        return f'Заказ №{str(Order.num_order).zfill(6)}.'

    class Meta:
        verbose_name_plural = 'Товары в заказах'
        verbose_name = 'Товар в заказе'
        ordering = ['product', 'count_product_in_order']

testing/task3/OnlineSofaProject/store_app/views/AddNewCommentView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View

from store_app.models import Product, Comment


class AddNewCommentView(LoginRequiredMixin, View):
    """Класс добавления комментария (мнения по товару, его оценка)"""

    def post(self, request):
        response_data = {}
        try:
            rating = request.POST.get('rating')
            text_comment = request.POST.get('text_comment')
            commented_product = Product.objects.get(pk=request.POST.get('product_id'))

            Comment.objects.create(rating=int(rating), text_comment=text_comment,
                                   author_comment=request.user, product=commented_product)

            response_data['status'] = 'OK'
            response_data['rating'] = rating
            response_data['text_comment'] = text_comment
            response_data['user'] = request.user.username
            return JsonResponse(response_data)

        except Exception as e:
            print(e)
            response_data['status'] = 'BAD'
            return JsonResponse(response_data)

testing/task3/OnlineSofaProject/store_app/views/AddProductToCartView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import AnonymousUser
from django.http import JsonResponse
from django.views import View

from store_app.models import Product, WarehouseProducts, CartUser


class AddProductToCartView(View, LoginRequiredMixin):
    """Класс добавления товара в корзину пользователя"""

    def post(self, request):
        response_data = {}
        product_to_add_cart = Product.objects.get(pk=request.POST.get('product_id'))

        try:
            product_in_warehouse = WarehouseProducts.objects.get(product=product_to_add_cart)
            """Проверка если пользователь ввел число, превышающее кол-во товара на складе,
            если превышает, то страница остается без изменений, в корзину ничего не добавляется"""
            if product_in_warehouse.count_products < int(request.POST.get('count_product')):
                response_data['status'] = 'MORE'
                return JsonResponse(response_data)

            cart_current_user = CartUser.objects.filter(user=request.user)
            if len(cart_current_user) != 0:
                """Если корзина пользователя уже есть, и он добавлял ранее какой-то товар"""
                cart_current_user[0].products.add(product_to_add_cart)
                try:
                    """Если позиция данного товара уже в корзине и пользователь еще хочет добавить несколько товаров 
                    одной позиции """
                    product_in_cart = cart_current_user[0].productincart_set.get(product=product_to_add_cart)
                    product_in_cart.count_product_in_cart = product_in_cart.count_product_in_cart + \
                                                            int(request.POST.get('count_product'))
                    product_in_cart.save()

                except Exception as e:
                    print(e)
                    """В существующую корзину добавляется новый товар и указывается количество"""
                    cart_current_user[0].productincart_set.create(product=product_to_add_cart,
                                                                  count_product_in_cart=request.POST.get(
                                                                      'count_product'))

            else:
                """Иначе создается корзина, и добавляется первый товар в корзину"""
                cart_current_user = CartUser(user=request.user)
                cart_current_user.save()
                cart_current_user.products.add(Product.objects.get(pk=request.POST.get('product_id')))
                cart_current_user.productincart_set.create(product=product_to_add_cart,
                                                           count_product_in_cart=request.POST.get('count_product'))

            """Кол-во этого товара теперь на складе уменьшается"""

            product_in_warehouse.count_products -= int(request.POST.get('count_product'))
            product_in_warehouse.save()

            response_data['status'] = 'OK'
            return JsonResponse(response_data)
        except Exception as e:
            print(e)
            print(request.user == AnonymousUser)
            response_data['status'] = 'BAD'
            return JsonResponse(response_data)

testing/task3/OnlineSofaProject/store_app/views/ContactsPageView.py
from django.shortcuts import render
from django.views import View


class ContactsPageView(View):
    """Класс просмотра страницы с контактами"""

    def get(self, request):
        return render(request, 'contacts.html')

testing/task3/OnlineSofaProject/store_app/views/DeleteProductInCartView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View

from store_app.models import Product, ProductInCart, CartUser, WarehouseProducts


class DeleteProductInCartView(View, LoginRequiredMixin):
    """Удаление товара (только одной позиции!!!) из корзины"""

    def post(self, request):
        response_data = {}
        try:
            product = Product.objects.get(pk=request.POST.get('product_id'))

            """Удаление товара из таблицы CartUser"""
            request.user.cartuser.products.remove(product)

            """Удаление из таблицы ProductInCart"""
            ProductInCart.objects.get(cart_user=CartUser.objects.get(user=request.user),
                                      product=product).delete()

            """Восполнение запасов на складе данной позициии товара"""
            product_in_warehouse = WarehouseProducts.objects.get(product=product)
            product_in_warehouse.count_products += int(request.POST.get('count_products').split()[0])
            product_in_warehouse.save()

            response_data['status'] = 'OK'
            response_data['id'] = request.POST.get('product_id')
            return JsonResponse(response_data)

        except Exception as e:
            print(e)
            response_data['status'] = 'BAD'
            return JsonResponse(response_data)

testing/task3/OnlineSofaProject/store_app/views/FeedbackFormView.py
from django.http import JsonResponse
from django.views import View

from store_app.models import FeedBackWithClient


class FeedbackFormView(View):
    """Класс обработки отправки данных на заявку по получению обратной связи"""

    def post(self, request):
        response_data = {}
        try:
            FeedBackWithClient.objects.create(
                name_client=request.POST.get('name'),
                phone_client=request.POST.get('phone'),
                email_client=request.POST.get('email'),
                question_client=request.POST.get('question')
            )
            response_data['status'] = 'OK'

        except Exception as e:
            print(e)
            response_data['status'] = 'BAD'

        return JsonResponse(response_data)

testing/task3/OnlineSofaProject/store_app/views/GeneratePdfOrderDetailsView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import FileResponse
from django.shortcuts import redirect
from django.views import View

from store_app.accessory_modules import GeneratePdfDetailsOrder
from store_app.models import Order


class GeneratePdfOrderDetailsView(View, LoginRequiredMixin):

    def get(self, request, num_str):
        """Данные, которые нужно записать в pdf"""
        try:
            order = Order.objects.get(num_order=num_str)
            generation_pdf = GeneratePdfDetailsOrder(order, num_str)
            result_pdf = generation_pdf.generate_pdf()

            return FileResponse(result_pdf, as_attachment=False, filename=f'Заказ №{num_str}.pdf')

        except Exception as e:
            print(e)
            return redirect('user_cart_page')

testing/task3/OnlineSofaProject/store_app/views/HistoryOrdersView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect
from django.views import View

from store_app.models import Order


class HistoryOrdersView(View, LoginRequiredMixin):
    """Класс просмотра истории заказов"""

    def get(self, request):
        """Получение истории страницы заказов"""
        try:
            orders = Order.objects.filter(buyer_email=request.user.email)
            return render(request, 'order_history_page.html',
                          {'orders': orders})
        except Exception as e:
            print(e)
            return redirect('home')

testing/task3/OnlineSofaProject/store_app/views/HomepageView.py
from django.shortcuts import render
from django.views import View

from store_app.models import Product, Rubric


class HomepageView(View):
    """Класс просмотра домашней страницы: на ней отображаются товары-новинки"""

    def get(self, request):
        new_products = Product.objects.all()[:6]
        rubrics = Rubric.objects.all()
        context = {'new_products': new_products, 'rubrics': rubrics}
        return render(request, 'home.html', context)

testing/task3/OnlineSofaProject/store_app/views/IncreaseCountProductsView.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.views import View

from store_app.models import Product, ProductInCart, CartUser, WarehouseProducts


class IncreaseCountProductsView(View, LoginRequiredMixin):
    """Увеличение числа одной позиции товара в корзине на 1"""

    def post(self, request):
        response_data = {}
        try:
            product = Product.objects.get(pk=request.POST.get('product_id'))

            product_in_cart = ProductInCart.objects.get(cart_user=CartUser.objects.get(user=request.user),
                                                        product=product)

            """Проверка наличия еще 1 экземпляра товара"""
            product_in_warehouse = WarehouseProducts.objects.get(product=product)
            if product_in_warehouse.count_products >= 1:
                """Товар на складе есть"""
                product_in_cart.count_product_in_cart += 1
                product_in_cart.save()

                """Уменьшение запасов на складе данной позициии товара на 1"""
                product_in_warehouse.count_products -= 1
                product_in_warehouse.save()

                response_data['status'] = 'OK'
                response_data['id'] = request.POST.get('product_id')
                response_data['price'] = product.price

            else:
                """Товар на складе нет"""
                response_data['status'] = 'Not available'

            return JsonResponse(response_data)
        except Exception as e:
            print(e)
            response_data['status'] = 'BAD'
            return JsonResponse(response_data)

testing/task3/OnlineSofaProject/templates/store_app/contacts.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Контакты
{% endblock title %}

{% block content %}
    <h2>Адрес магазина (пункт самовывоза)</h2>
    <p>г.Екатеринбург Ул.Крауля 57</p>
    <div id="map" style="width: 600px; height: 400px"></div>
{% endblock content %}

{% block scripts %}
    <script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU" type="text/javascript"></script>
    <script type="text/javascript" src="{% static 'js/ya_map.js' %}"></script>
{% endblock scripts %}

testing/task3/OnlineSofaProject/templates/store_app/home.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Главная
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/homepage_styles.css' %}" />
{% endblock styles %}


{% block content %}
<div class="container-fluid text-center">
    <div class="row content">
        <div class="col-sm-2 sidenav" id="list_rubrics">
            <h3>Выбрать рубрику:</h3>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">
                    Список рубрик<span class="caret"></span>
                </button>
                <ul class="dropdown-menu">
                    {% for rubric in rubrics %}
                    <li><a href="{% url 'products_by_rubric' rubric.pk %}">{{ rubric.name }}</a></li><hr>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-sm-8 text-left">
            <div class="container">
                <div class="list-inline">
                    <p class="lead">Cортировка</p>
                    <select class="form-control" id="choice_sorting" onchange="window.location.href=this.options[this.selectedIndex].value">
                        <option VALUE="{% url 'sorting_products' 'increase_price' %}">Дешевые сверху</option>
                        <option VALUE="{% url 'sorting_products' 'decrease_price' %}">Дорогие сверху</option>
                        <option VALUE="{% url 'sorting_products' 'top_rating' %}">Высокий рейтинг по отзывым</option>
                        <option VALUE="{% url 'sorting_products' 'many_reviews' %}">Много отзывов</option>
                        <option selected VALUE="{% url 'home' %}">По популярности</option>
                    </select>
                    <br>
                </div>
                <div class="row">
                    {% for product in new_products %}
                    <div class="col-sm-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <p align="center"><a href="{% url 'product_details' product.pk %}">{{ product.title }}</a></p>
                            </div>

                            <div class="panel-body" id="product_image" align="center">
                                  <div id="carousel_{{ forloop.counter }}" class="carousel slide" data-ride="carousel">
                                      <div class="carousel-inner">
                                          {% for image_product in product.imageproduct_set.all %}

                                          {% if forloop.first %}
                                            <div class="item active">
                                              <img src="{{ image_product.image.url }}" alt="{{ product.title }}" width="240px" height="210px" class="img-thumbnail">
                                            </div>
                                          {% else %}
                                            <div class="item">
                                              <img src="{{ image_product.image.url }}" alt="{{ product.title }}" width="240px" height="210px" class="img-thumbnail">
                                            </div>
                                          {% endif %}

                                          {% endfor %}
                                      </div>
                                      <a class="left carousel-control" href="#carousel_{{ forloop.counter }}" role="button" data-slide="prev">
                                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                            <span class="sr-only">Предыдущий</span>
                                      </a>
                                      <a class="right carousel-control" href="#carousel_{{ forloop.counter }}" role="button" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                        <span class="sr-only">Следующий</span>
                                      </a>
                                    </div>
                            </div>

                            <div class="panel-footer">
                                <p>Цена: {{ product.price }}</p>
                                <p>Бренд: {{ product.brand }}</p>
                                {% if product.avg_rating == -1 %}
                                <p>Оценок нет</p>
                                {% else %}
                                <p>Рейтинг: <abbr title="Количество отзывов: {{ product.comments.count }}">{{ product.avg_rating }}</abbr></p>
                                {% endif %}
                                <form method="POST" action="{% url 'add_product_to_basket' %}" id="add_product_to_basket">
                                    {% csrf_token %}
                                    <button type="submit" id="add_to_cart">
                                        Положить в корзину<span class="glyphicon glyphicon-shopping-cart"></span>
                                    </button>
                                    <input type="hidden" name="product_id_to_basket" value="{{ product.id }}" id="product_id_to_basket">
                                    <input type="hidden" id="number" value="1" name="number">
                                </form>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div><br>
        </div>
        <div class="col-sm-2 sidenav">
          <div class="well">
            <p>ADS</p>
          </div>
          <div class="well">
            <p>ADS</p>
          </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/add_product_to_basket.js' %}"></script>
{% endblock scripts %}

testing/task3/OnlineSofaProject/templates/store_app/order_history_page.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    История ваших заказов
{% endblock title %}

{% block styles %}
<link rel="stylesheet" href="{% static 'css/order_history_page.css' %}" />
{% endblock styles %}


{% block content %}
<div class="container-fluid text-center">
    <div class="row content">
        <div class="col-sm-2 sidenav" id="myScrollspy">
            <h3>Номера заказов</h3>
            <ul class="nav nav-pills nav-stacked">
                {% for order in orders %}

                    <li><a href="#info_order_{{ forloop.counter }}">№{{ order.num_order }}</a></li>

                {% endfor %}
            </ul>

        </div>
        <div class="col-sm-8 text-left">
            <div class="container">
                <div class="row">
                    <h1 align="center">История ваших заказов</h1>
                    {% for order in orders %}
                        <div class="well" id="info_order_{{ forloop.counter }}">
                            <h2>Заказ №{{ order.num_order }}</h2>
                            <h6>Дата: {{ order.created_at }}</h6>
                            {% for product_in_order in order.productsinorder_set.all %}
                            <div class="media">
                                <div class="media-left">
                                    <img src="{{ product_in_order.product.imageproduct_set.first.image.url }}" alt="{{ product.title }}" width="100" height="100">
                                </div>
                                <div class="media-body">
                                    <h4 class="media-heading">
                                        <a href="{% url 'product_details' product_in_order.product.id %}">{{ product_in_order.product }}</a>
                                    </h4>
                                    <p>Количество: {{ product_in_order.count_product_in_order }}</p>
                                    <p>Цена (за штуку): {{ product_in_order.product.price }}</p>
                                </div>
                            </div>
                            <hr>
                            {% endfor %}
                            <h4><strong>Итог заказа:</strong>{{ order.total_sum}}</h4>
                        </div>


                    {% endfor %}
                </div>
            </div><br>
        </div>
        <div class="col-sm-2 sidenav">
          <div class="well">
            <p>ADS</p>
          </div>
          <div class="well">
            <p>ADS</p>
          </div>
        </div>
    </div>
</div>
{% endblock content %}

testing/task3/OnlineSofaProject/templates/store_app/pdf_details_order.html
<html>
    <head>

    </head>
    <body>
        <h1>{{ num }}</h1>
    </body>
</html>

testing/task3/OnlineSofaProject/templates/store_app/products_by_rubric.html
{% extends 'base.html' %}

{% block title %}
    Товары по выбранной рубрике: {{ rubric.name }}
{% endblock title %}

{% block content %}
<div class="container-fluid text-center">
    <div class="row content">
        <div class="col-sm-2 sidenav" id="list_rubrics">
            <h3>Выбрать рубрику:</h3>
            <div class="dropdown">
                <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">Список рубрик
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                    {% for rubric in rubrics %}
                    <li><a href="{% url 'products_by_rubric' rubric.pk %}">{{ rubric.name }}</a></li><hr>
                    {% endfor %}
                </ul>
            </div>
        </div>
        <div class="col-sm-8 text-left" id="products_selected_rubric">
            <h1>Выбранная рубрика: {{ selected_rubric }}</h1>
            <div class="container">
                <div class="row">
                    {% for product in products %}
                    <div class="col-sm-4">
                        <div class="panel panel-default">
                            <div class="panel-heading"><p align="center"><a href="{% url 'product_details' product.pk %}">{{ product.title }}</a></p></div>
                            <div class="panel-body" id="product_image" align="center">
                                  <div id="carousel_{{ forloop.counter }}" class="carousel slide" data-ride="carousel">
                                      <div class="carousel-inner">
                                          {% for image_product in product.imageproduct_set.all %}
                                          {% if forloop.first %}
                                            <div class="item active">
                                              <img src="{{ image_product.image.url }}" alt="{{ product.title }}" width="240px" height="210px" class="img-thumbnail">
                                            </div>
                                          {% else %}
                                            <div class="item">
                                              <img src="{{ image_product.image.url }}" alt="{{ product.title }}" width="240px" height="210px" class="img-thumbnail">
                                            </div>
                                          {% endif %}
                                          {% endfor %}
                                      </div>
                                      <a class="left carousel-control" href="#carousel_{{ forloop.counter }}" role="button" data-slide="prev">
                                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                                            <span class="sr-only">Предыдущий</span>
                                      </a>
                                      <a class="right carousel-control" href="#carousel_{{ forloop.counter }}" role="button" data-slide="next">
                                        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                                        <span class="sr-only">Следующий</span>
                                      </a>
                                    </div>
                            </div>
                            <div class="panel-footer">
                                <p>Цена: {{ product.price }}</p>
                                <p>Бренд: {{ product.brand }}</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div><br>
        </div>
        <div class="col-sm-2 sidenav">
          <div class="well">
            <p>ADS</p>
          </div>
          <div class="well">
            <p>ADS</p>
          </div>
        </div>
    </div>
</div>

{% endblock content %}